pipeline {
    stages {
        parallel {
            stage('Build') {
                echo 'Building the project...'
            }
            stage('Test') {
                echo 'Running tests...'
            }
        }
    }
}